Algoritmo "EstruturaEnquanto"
// Disciplina  : Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Estrutura de repetição usando ENQUANTO
// Autor(a)    : Raquel Alves de Queiroz
// Data atual  : 12/09/2025
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto numero<10 faca
      escreval("Raquel")
      numero<-numero+1
   fimenquanto

Fimalgoritmo