Algoritmo "EstruturadeDecisaoSimples"

// Disciplina  : Lógica de Programação
// Descrição   : Exemplo de Estrutura de Decisão Simples
// Autor(a)    : Raquel Alves de Queiroz
// Data atual  : 03/09/2025

Var
   // Seção de Declarações das variáveis
   idade:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite sua idade: ")
   Leia(idade)
   se idade <18 entao
      Escreval("Você é menor de idade!")
   fimse

Fimalgoritmo