Algoritmo "ContagemRegressiva"
// Descrição   : Mostre uma contagem regressiva de 10 até 1
// usando o laço repita.
// Professor   : Jailson Costa dos Santos
// Autor(a)    : Raquel Alves de Queiroz
// Data atual  : 19/09/2025
Var
   // Seção de Declarações das variáveis
   contadora:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contadora<-10
   repita
   escreval(contadora)
   contadora<-contadora-1
   ate contadora<1
   

Fimalgoritmo