Algoritmo "Numeros1Ate10"
// Descrição   : Exibe os números de 1 até 10
// Professor   : Jailson Costa dos Santos
// Autor(a)    : Raquel Alves de Queiroz
// Data atual  : 19/09/2025
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 1 ate 10 passo 1 faca
   escreval(contadora)
   fimpara

Fimalgoritmo